default_job = "run-producer"
env.CARGO_TERM_COLOR = "always"

[keybindings]
p = "job:run-producer"
c = "job:run-consumer"

[jobs.test]
clear = false # Keep output on screen
display = "always" # Ensure output is displayed
command = [
  "cargo",
  "+nightly",
  "nextest",
  "run",
  "--all-features",
  "--verbose",
  "--failure-output",
  "final", # or final
  "--success-output",
  "final",
]

# Run your long-running application (eg server) and have the result displayed in bacon.
# For programs that never stop (eg a server), `background` is set to false
# to have the cargo run output immediately displayed instead of waiting for
# program's end.
# 'on_change_strategy' is set to `kill_then_restart` to have your program restart
# on every change (an alternative would be to use the 'F5' key manually in bacon).
# the job uses the cranelift compiler form nightly to reduce compilation time with ~33%.
[jobs.run-producer]
command = [
  "cargo",
  "+nightly",
  "run",
  "-Zcodegen-backend",
  "--all-features",
  # put launch parameters for your program behind a `--` separator
  "-p",
  "streamit",
   "--bin",
  "producer",
]
need_stdout = true
allow_warnings = true
background = false
on_change_strategy = "kill_then_restart"
ignore = ["**/generated_at_build.rs"]

# Run your long-running application (eg server) and have the result displayed in bacon.
# For programs that never stop (eg a server), `background` is set to false
# to have the cargo run output immediately displayed instead of waiting for
# program's end.
# 'on_change_strategy' is set to `kill_then_restart` to have your program restart
# on every change (an alternative would be to use the 'F5' key manually in bacon).
# the job uses the cranelift compiler form nightly to reduce compilation time with ~33%.
[jobs.run-consumer]
command = [
  "cargo",
  "+nightly",
  "run",
  "-Zcodegen-backend",
  "--all-features",
  # put launch parameters for your program behind a `--` separator
  "-p",
  "streamit",
   "--bin",
  "consumer",
]
need_stdout = true
allow_warnings = true
background = false
on_change_strategy = "kill_then_restart"

