[package]
name = "streamit"
version = "0.1.0"
edition = "2024"

[lib]
name = "streamitlib"
path = "src/lib.rs"
doctest = false

[dependencies]
tokio = {workspace=true}

[[bin]]
name = "producer"
path = "src/producer.rs"

[[bin]]
name = "consumer"
path = "src/consumer.rs"
