[package]
name = "streamit"
version = "0.1.0"
edition = "2024"

[lib]
name = "streamitlib"
path = "src/lib.rs"
doctest = false

[dependencies]
anyhow.workspace = true
bilrost = "0"
fluvio = "0.24"
nanoid.workspace = true
serde.workspace=true
time.workspace=true
tokio.workspace=true
tracing.workspace = true
tracing-subscriber.workspace = true

[[bin]]
name = "producer"
path = "src/producer.rs"

[[bin]]
name = "consumer"
path = "src/consumer.rs"
