[package]
name = "streamit"
version = "0.1.0"
edition = "2024"
license = "MIT"

[lib]
name = "streamitlib"
path = "src/lib.rs"
doctest = false

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bilrost.workspace = true
fluvio.workspace = true
fluvio-protocol.workspace = true
futures.workspace = true
serde.workspace=true
thiserror.workspace=true
time.workspace=true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
tracing-test.workspace = true

[[bin]]
name = "producer"
path = "src/main_producer.rs"

[[bin]]
name = "consumer"
path = "src/main_consumer.rs"
