[package]
name = "streamit"
version = "0.1.0"
edition = "2024"

[lib]
name = "streamitlib"
path = "src/lib.rs"
doctest = false

[dependencies]
anyhow.workspace = true
bilrost = "0"
fluvio = "0.24"
futures = "0.3.31"
serde.workspace=true
time.workspace=true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
criterion = { version = "0", features= ["async_tokio"] }

[[bin]]
name = "producer"
path = "src/main_producer.rs"

[[bin]]
name = "consumer"
path = "src/main_consumer.rs"

[[bench]]
name = "benchmark"
harness = false
